"""
Data models for the image-to-diagram pipeline
"""

from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, Any, List
from pathlib import Path
from datetime import datetime
import json


@dataclass
class ImageInfo:
    """Information about an image file"""
    path: Path
    filename: str
    width: Optional[int] = None
    height: Optional[int] = None
    format: Optional[str] = None
    size_bytes: Optional[int] = None

    # Optional context from PDF extraction
    caption: Optional[str] = None
    page_number: Optional[int] = None
    figure_label: Optional[str] = None  # e.g., "Figure 1", "Fig. 3a"
    context_text: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary, handling Path objects"""
        d = asdict(self)
        d['path'] = str(self.path)
        return d

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ImageInfo':
        """Create from dictionary"""
        data = data.copy()
        if 'path' in data:
            data['path'] = Path(data['path'])
        return cls(**data)


@dataclass
class StructuredDescription:
    """Structured description of an image generated by LLM"""

    # Core fields
    diagram_type: str  # e.g., "flowchart", "architecture", "network"
    title: str
    summary: str

    # Detailed structure
    components: List[Dict[str, Any]] = field(default_factory=list)
    # Each component: {"id": str, "type": str, "label": str, "description": str}

    relationships: List[Dict[str, Any]] = field(default_factory=list)
    # Each relationship: {"source": str, "target": str, "type": str, "label": str}

    spatial_layout: Optional[Dict[str, Any]] = None
    # e.g., {"type": "hierarchical", "direction": "top-to-bottom", "layers": [...]}

    color_scheme: Optional[Dict[str, str]] = None
    # e.g., {"primary": "#4A90E2", "secondary": "#7ED321"}

    annotations: List[str] = field(default_factory=list)
    # Additional text annotations or notes

    metadata: Dict[str, Any] = field(default_factory=dict)
    # Generation metadata: timestamp, model, confidence, etc.

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'StructuredDescription':
        """Create from dictionary"""
        return cls(**data)

    def to_json(self, indent: int = 2) -> str:
        """Convert to JSON string"""
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)


@dataclass
class DiagramXML:
    """Drawio XML diagram with metadata"""
    xml_content: str
    diagram_type: str
    node_count: int = 0
    edge_count: int = 0

    # Validation info
    is_valid: bool = True
    validation_errors: List[str] = field(default_factory=list)

    # Generation metadata
    model_used: Optional[str] = None
    generation_time: Optional[float] = None
    repair_attempts: int = 0

    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'DiagramXML':
        """Create from dictionary"""
        return cls(**data)


@dataclass
class ProcessingResult:
    """Result of processing a single image"""
    image_info: ImageInfo

    # Screening result (for workflow 1)
    is_candidate: Optional[bool] = None
    screening_score: Optional[float] = None
    screening_reason: Optional[str] = None

    # Description result
    description: Optional[StructuredDescription] = None
    description_success: bool = False
    description_error: Optional[str] = None

    # Diagram result
    diagram: Optional[DiagramXML] = None
    diagram_success: bool = False
    diagram_error: Optional[str] = None

    # Rendering result
    rendered_path: Optional[Path] = None
    rendering_success: bool = False
    rendering_error: Optional[str] = None

    # Timing info
    total_time: Optional[float] = None
    processing_timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    # Token usage statistics
    token_usage: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary, handling nested objects"""
        d = {
            'image_info': self.image_info.to_dict(),
            'is_candidate': self.is_candidate,
            'screening_score': self.screening_score,
            'screening_reason': self.screening_reason,
            'description': self.description.to_dict() if self.description else None,
            'description_success': self.description_success,
            'description_error': self.description_error,
            'diagram': self.diagram.to_dict() if self.diagram else None,
            'diagram_success': self.diagram_success,
            'diagram_error': self.diagram_error,
            'rendered_path': str(self.rendered_path) if self.rendered_path else None,
            'rendering_success': self.rendering_success,
            'rendering_error': self.rendering_error,
            'total_time': self.total_time,
            'processing_timestamp': self.processing_timestamp,
            'token_usage': self.token_usage
        }
        return d

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ProcessingResult':
        """Create from dictionary"""
        data = data.copy()

        if 'image_info' in data and data['image_info']:
            data['image_info'] = ImageInfo.from_dict(data['image_info'])

        if 'description' in data and data['description']:
            data['description'] = StructuredDescription.from_dict(data['description'])

        if 'diagram' in data and data['diagram']:
            data['diagram'] = DiagramXML.from_dict(data['diagram'])

        if 'rendered_path' in data and data['rendered_path']:
            data['rendered_path'] = Path(data['rendered_path'])

        return cls(**data)


@dataclass
class PaperMetadata:
    """Metadata for a paper (workflow 1)"""
    paper_id: str
    title: Optional[str] = None
    authors: List[str] = field(default_factory=list)
    venue: Optional[str] = None
    year: Optional[int] = None

    # MinerU parsing info
    parsed_path: Optional[Path] = None
    total_pages: Optional[int] = None
    total_images: Optional[int] = None

    # Processing stats
    images_screened: int = 0
    images_kept: int = 0
    images_processed: int = 0

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        d = asdict(self)
        if self.parsed_path:
            d['parsed_path'] = str(self.parsed_path)
        return d

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'PaperMetadata':
        """Create from dictionary"""
        data = data.copy()
        if 'parsed_path' in data and data['parsed_path']:
            data['parsed_path'] = Path(data['parsed_path'])
        return cls(**data)
